name = "chasemycareer-backend"
main = "src/index.ts"
compatibility_date = "2024-01-01"
node_compat = true

[build]
command = "npm run build"

[[d1_databases]]
binding = "DB"
database_name = "chasemycareer-db"
database_id = "4a78cd66-9f12-45fb-9543-03d2f1830c48"

[env.production]
name = "chasemycareer-backend-production"

[[env.production.d1_databases]]
binding = "DB"
database_name = "chasemycareer-db-production"
database_id = "4a78cd66-9f12-45fb-9543-03d2f1830c48"